node{
  checkout scm
  stage('Build'){
    echo 'Builing....'
    sh 'mvn clean'
    echo 'cleaned'
    sh 'mvn build'
    echo 'built'
  }
  stage('Test'){
    echo 'Testing...'
  }
  stage('Deploy'){
    echo 'Deploying..'
  }
}
