node{
  checkout scm
  stage('Build'){
    echo 'Builing....'
 //   git url: 'git@github.com:Rudu12/microservices.git'
    def mvn_version = 'Maven'
    withEnv( ["PATH+MAVEN=${tool mvn_version}/bin"] ) {
    sh 'mvn clean -f MicroServicesOnCloud'
    echo 'cleaned'
    //sh 'mvn build'
    //echo 'built'
}
   
  }
  stage('Test'){
    echo 'Testing...'
  }
  stage('Deploy'){
    echo 'Deploying..'
  }
}
